name: CI Java - DÃ­a 3 (Cache Maven)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar cache de Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('java_project/pom.xml') }}
          restore-keys: |
            maven-

      - name: Compilar proyecto
        run: mvn -B -f java_project/pom.xml compile

      - name: Ejecutar tests
        run: mvn -B -f java_project/pom.xml test
