name: CI/CD con Environments (DÃ­a 7)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Ambiente de despliegue"
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  deploy:
    name: Deploy a ambiente seleccionado
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Print environment info
        run: |
          echo "Desplegando en: ${{ inputs.environment }}"
          echo "Variable global: ${{ vars.APP_ENV }}"
          echo "URL: ${{ vars.API_URL }}"

      - name: Usar secrets del environment
        run: |
          echo "Usando secret..."
        env:
          API_KEY: ${{ secrets.API_KEY }}
